#!/bin/sh

set -e

# Default depth is 1
depth=1

# Depth can be orderidden as an option
leftOver=""
until [ -z $1 ]
    do
    if [ "$1" == "--depth" ]; then
        shift
        if [ "$1" -eq "$1" ] 2>/dev/null; then
            depth="$1"
            shift
        else
            echo "--depth option needs a following number"
            exit 1
        fi
    else
        leftOver="${leftOver} $1"
        shift
    fi
done
if [ ! -z "${leftOver// }" ]; then
    echo "Unrecognized params/options: $leftOver"
    exit 1
fi

# Can only go ahead if a git repo
not_a_git_repo=$(git status | grep "Not a git repository" | wc -l)
if [ "$not_a_git_repo" -gt "0" ]
then
  echo "This isn't a Git repository, can't run 'git slim' here"
  exit 1
fi

# Can only go ahead if there is nothing pending
changed_lines=$(git status --porcelain | wc -l)
if [ "$changed_lines" -gt "0" ]
then
  echo "There are untracked changes - meaning it is inappropriate to slim this repository"
  exit 1
fi

# Can only go ahead if there is nothing taht should be pushed
ahead_of_remote=$(git status | grep "Your branch is ahead" | wc -l)
if [ "$ahead_of_remote" -gt "0" ]
then
  echo "There are local commits not pushed the default remote - meaning it is inappropriate to slim this repository"
  exit 1
fi

# Do it, using temp directory
mkdir .git_slimmer
git clone --bare --depth=$depth  file://"$PWD" .git_slimmer
rm -rf .git/objects
mv .git_slimmer/{shallow,objects} .git
rm -rf .git_slimmer
